[package]
name = "bevy_async_system"
version = "0.3.0"
edition = "2021"
authors = ["elm"]
categories = ["asynchronous", "game-development"]
description = "Provides the ability to wait for game status asynchronously."
keywords = ["game", "gamedev", "bevy", "async"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/not-elm/bevy_async_system"


[[example]]
name = "wait_audio"
path = "examples/wait/wait_for_audio_playback_to_finish.rs"

[[example]]
name = "move_shape"
path = "examples/wait/move_shape.rs"


[dependencies]
bevy = { version = "0.13.0", default-features = false }
store = { path = "../store" }
futures-lite = "2.2.0"


[dev-dependencies]
bevy = { version = "0.13.0" }
reqwest = "0.11.25"
futures = "0.3.30"