[package]
name = "bevy_flurx"
version = "0.3.2-beta.0"
edition = "2021"
authors = ["elm"]
categories = ["asynchronous", "game-development"]
description = "Provides the ability to wait for game status asynchronously."
keywords = ["game", "gamedev", "bevy", "async"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/not-elm/bevy_flurx"

[workspace]
exclude = ["benches"]

[[example]]
name = "delay"
path = "examples/simple/delay.rs"

[[example]]
name = "once"
path = "examples/simple/once.rs"

[[example]]
name = "wait"
path = "examples/simple/wait.rs"

[[example]]
name = "sequence"
path = "examples/simple/sequence.rs"

[[example]]
name = "wait_stop_audio"
path = "examples/audio/wait_stop_audio.rs"

[[example]]
name = "move_shape"
path = "examples/gui/move_shape.rs"

[[bench]]
name = "cmp_countup"
path = "benches/cmp_countup.rs"
harness = false
#
[[bench]]
name = "cmp_repeat_countup"
path = "benches/cmp_repeat_countup.rs"
harness = false

[[bench]]
name = "sequence"
path = "benches/sequence.rs"
harness = false

[dependencies]
bevy = { version = "0.13.1", default-features = false }
flurx = { version = "0.1.3", features = ["sync"] }
futures-lite = "2.2.0"
futures-polling = "0.1.1"

[dev-dependencies]
bevy = { version = "0.13.1" }
bevy_test_helper = { git = "https://github.com/not-elm/bevy_test_helper" }
reqwest = "0.12.2"
futures = "0.3.30"
criterion = "0.5.1"

[features]
default = ["audio"]
audio = ["bevy/bevy_audio", "bevy/bevy_asset"]

[workspace.lints.clippy]
type_complexity = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
undocumented_unsafe_blocks = "warn"
redundant_else = "warn"
match_same_arms = "warn"
semicolon_if_nothing_returned = "warn"

[workspace.lints.rust]
missing_docs = "warn"

[lints]
workspace = true