[package]
name = "bevy_async_system"
version = "0.1.1"
edition = "2021"
authors = ["elm"]
categories = ["asynchronous", "game-development"]
description = "Provides the ability to wait for game status asynchronously."
keywords = ["game", "gamedev", "bevy", "async"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/elmtw/bevy_async_system"


[dependencies]
bevy = { version = "0.13.0", default-features = false }
store = { path = "../store" }
futures-lite = "2.2.0"
