[package]
name = "bevy_flurx"
version = "0.3.0"
edition = "2021"
authors = ["elm"]
categories = ["asynchronous", "game-development"]
description = "Provides the ability to wait for game status asynchronously."
keywords = ["game", "gamedev", "bevy", "async"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/not-elm/bevy_flurx"

[[example]]
name = "delay"
path = "examples/simple/delay.rs"

[[example]]
name = "once"
path = "examples/simple/once.rs"

[[example]]
name = "wait"
path = "examples/simple/wait.rs"

[[example]]
name = "wait_stop_audio"
path = "examples/audio/wait_stop_audio.rs"

[[example]]
name = "move_shape"
path = "examples/gui/move_shape.rs"


[dependencies]
bevy = { version = "0.13.0", default-features = false }
flurx = { version = "0.1.3", features = ["sync"] }
futures-lite = "2.2.0"
futures-polling = "0.1.1"

[dev-dependencies]
bevy = { version = "0.13.0" }
reqwest = "0.11.25"
futures = "0.3.30"